### PR TITLE
Improve error handling in `imageDimensionsFromData`

### PR DESCRIPTION
**Pull request by fabon-f**
Passing an incomplete binary to `imageDimensionsFromData` can raise `RangeError` in the current implementation. This error can occur in particular through `imageDimensionsFromStream`.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Would you be able to provide a test?

Maybe we could detect such a case and exist early even before an error is thrown.

**Comment by fabon-f** [comment]
I added the test.

For better error handling, I think checking offset every time would be better. Should I implement this in this PR, or in other PR?

**Comment by sindresorhus** [comment]
> I think checking offset every time would be better. Should I implement this in this PR, or in other PR?

👍 In this PR.

**Comment by sindresorhus** [comment]
Thanks :)

**Pull request merged**
